- src/global.css
fixed position background image in global.css
> fixed background image

- src/App.js
- src/ui/pages/login/index.js
- src/ui/pages/login/login.jsx
- src/ui/pages/login/loginStyle.jsx
- src/ui/pages/register/register.jsx
- src/ui/pages/register/registerStyle.jsx
create a login page add external CSS and add function on click to go to SignUp and SignIn page
> Sw01 login

- package-lock.json
- src/ui/pages/home/ui/components/homeTab/hometap.jsx
> homepage no pending bill

- frontend/.gitignore
- frontend/package-lock.json
- frontend/package.json
- frontend/src/index.js
- resolve a compatibility issues that cause from @mui by downgrading to version 17
- add two more dependencies which are toastify(for tosat message) and axios(for api)
> ↘️Downgrade react to version 17 and add more dependeccies

- frontend/package-lock.json
- frontend/src/App.js
- frontend/src/ui/pages/home/components/createBillButton.jsx
- frontend/src/ui/pages/home/style/hometabStyle.jsx
- frontend/src/ui/pages/splitingBill/components/bottomBar.jsx
- frontend/src/ui/pages/splitingBill/components/buttonAddItem.jsx
- frontend/src/ui/pages/splitingBill/components/itemList.jsx
- frontend/src/ui/pages/splitingBill/components/splittingBillTab.jsx
- frontend/src/ui/pages/splitingBill/splittingBill.jsx
- frontend/src/ui/pages/splitingBill/style/bottomBarStyle.js
- frontend/src/ui/pages/splitingBill/style/buttonAddItemStyle.js
- frontend/src/ui/pages/splitingBill/style/itemListStyle.js
- frontend/src/ui/pages/splitingBill/style/splittingBillTabStyle.js
create 4 components in splitting bill page
- splittingBillTab
- itemList
- buttonAddItem
- bottomBar
> create splitting bill components

- frontend/src/ui/pages/register/components/inputText.jsx
- frontend/src/ui/pages/register/register.jsx
- add require
- add confirm password
- disable button when password did not match
- change textField to components
> update register page

- .vscode/settings.json
- frontend/src/ui/pages/login/components/loginInputText.jsx
- frontend/src/ui/pages/login/login.jsx
- frontend/src/ui/pages/register/components/registerInputText.jsx
- frontend/src/ui/pages/register/register.jsx
update login and register page
> update login and register page

- .vscode/settings.json
- frontend/src/ui/pages/login/login.jsx
- frontend/src/ui/pages/register/components/registerInputText.jsx
- frontend/src/ui/pages/register/register.jsx
update notification login and register
> update notification login and register

- backend/sharewrap_backend/pom.xml
- backend/sharewrap_backend/src/main/java/com/sharewrap/sharewrap_backend/config/JwtAuthFilter.java
- backend/sharewrap_backend/src/main/java/com/sharewrap/sharewrap_backend/config/PasswordConfig.java
- backend/sharewrap_backend/src/main/java/com/sharewrap/sharewrap_backend/config/RestExceptionHandler.java
- backend/sharewrap_backend/src/main/java/com/sharewrap/sharewrap_backend/config/SecurityConfig.java
- backend/sharewrap_backend/src/main/java/com/sharewrap/sharewrap_backend/config/UserAuthEntryPoint.java
- backend/sharewrap_backend/src/main/java/com/sharewrap/sharewrap_backend/config/UserAuthProvider.java
- backend/sharewrap_backend/src/main/java/com/sharewrap/sharewrap_backend/config/WebConfig.java
- backend/sharewrap_backend/src/main/java/com/sharewrap/sharewrap_backend/controllers/AuthController.java
- backend/sharewrap_backend/src/main/java/com/sharewrap/sharewrap_backend/dtos/ErrorDto.java
- backend/sharewrap_backend/src/main/java/com/sharewrap/sharewrap_backend/dtos/LoginDto.java
- backend/sharewrap_backend/src/main/java/com/sharewrap/sharewrap_backend/dtos/RegisterDto.java
- backend/sharewrap_backend/src/main/java/com/sharewrap/sharewrap_backend/dtos/UserDto.java
- backend/sharewrap_backend/src/main/java/com/sharewrap/sharewrap_backend/exceptions/AppException.java
- backend/sharewrap_backend/src/main/java/com/sharewrap/sharewrap_backend/mappers/UserMapper.java
- backend/sharewrap_backend/src/main/java/com/sharewrap/sharewrap_backend/models/User.java
- backend/sharewrap_backend/src/main/java/com/sharewrap/sharewrap_backend/repositories/UserRepository.java
- backend/sharewrap_backend/src/main/java/com/sharewrap/sharewrap_backend/services/UserService.java
- backend/sharewrap_backend/src/test/java/com/sharewrap/sharewrap_backend/repository/UserRepositoryTests.java
- frontend/src/App.js
- frontend/src/helpers/axios_helper.js
- frontend/src/ui/pages/register/register.jsx
- Add security method for /register
- Fill in the API in frontend
- Add redirect to login page after login
- Add toast message for the error message of register
- Add Mapping plugin for backecnd
- Rearrange the plugin
> ✅SW111  Develop Security methdod

- frontend/src/App.js
- frontend/src/ui/pages/login/login.jsx
- frontend/src/ui/pages/register/register.jsx
- FIX register snackbar message
- ADD login API
- ADD redirect and timeout
> ✅SW19_ADD&FIX login method

- frontend/src/ui/modules/components/navbar.jsx
> ✅SW117 ADD logout method

- backend/.idea/backend.iml
- backend/.idea/compiler.xml
- backend/.idea/modules.xml
- backend/.idea/vcs.xml
- backend/sharewrap_backend/src/main/java/com/sharewrap/sharewrap_backend/controllers/BillController.java
- backend/sharewrap_backend/src/main/java/com/sharewrap/sharewrap_backend/controllers/ItemController.java
- backend/sharewrap_backend/src/main/java/com/sharewrap/sharewrap_backend/dtos/BillDto.java
- backend/sharewrap_backend/src/main/java/com/sharewrap/sharewrap_backend/dtos/ItemDto.java
- backend/sharewrap_backend/src/main/java/com/sharewrap/sharewrap_backend/mappers/BillMapper.java
- backend/sharewrap_backend/src/main/java/com/sharewrap/sharewrap_backend/mappers/ItemMapper.java
- backend/sharewrap_backend/src/main/java/com/sharewrap/sharewrap_backend/models/Bill.java
- backend/sharewrap_backend/src/main/java/com/sharewrap/sharewrap_backend/models/Item.java
- backend/sharewrap_backend/src/main/java/com/sharewrap/sharewrap_backend/models/User.java
- backend/sharewrap_backend/src/main/java/com/sharewrap/sharewrap_backend/repositories/BillRepository.java
- backend/sharewrap_backend/src/main/java/com/sharewrap/sharewrap_backend/repositories/ItemRepository.java
- backend/sharewrap_backend/src/main/java/com/sharewrap/sharewrap_backend/services/BillService.java
- backend/sharewrap_backend/src/main/java/com/sharewrap/sharewrap_backend/services/ItemService.java
- backend/sharewrap_backend/src/main/java/com/sharewrap/sharewrap_backend/services/UserService.java
- backend/sharewrap_backend/src/main/resources/application.properties
- frontend/src/App.js
- frontend/src/helpers/axios_helper.js
- frontend/src/ui/modules/components/protectedRoute.jsx
- frontend/src/ui/pages/home/components/createBillButton.jsx
- frontend/src/ui/pages/home/home.jsx
- frontend/src/ui/pages/login/login.jsx
- Add 'auth_user' to store into the localStorage  after logged in, so we can use the the data to do many things
- Add Bill, Item, User(friend) object
- Add path to Home, now it is home/{userId} not only /home anymore, pls becareful about this
- Add ProtectedRoute, now if you not logged in, you cannot view the protected page that rquired logged in.
- Add method for CRUD(haven't integrate and test with frontend yet)
> ☕SW25 Develop Bill Splitting

- frontend/src/ui/pages/splitingBill/components/bottomBar.jsx
- frontend/src/ui/pages/splitingBill/style/bottomBarStyle.js
And box between Bank and PromptPay button to give some space and make two buttons full width
> fixed gap between Bank and PromptPay button

- frontend/src/App.js
- frontend/src/ui/pages/addFriend/components/addFriendTab.jsx
- frontend/src/ui/pages/editBankAccount/components/editBankTab.jsx
- frontend/src/ui/pages/editBankAccount/editBankAccount.jsx
- frontend/src/ui/pages/editPromptpay/components/editPromptpayTab.jsx
- frontend/src/ui/pages/editPromptpay/editPromptpay.jsx
- frontend/src/ui/pages/splitingBill/components/bottomBar.jsx
- frontend/src/ui/pages/splitingBill/components/selectedBank.jsx
- frontend/src/ui/pages/splitingBill/components/selectedPromptpay.jsx
create edits for both bank account and prompt pay pages
remove 2 buttons from both pages (change UI)
> Sw218 create payment details

- backend/src/main/java/com/sharewrap/sharewrap_backend/controllers/UserController.java
- backend/src/main/java/com/sharewrap/sharewrap_backend/services/UserService.java
- frontend/src/ui/pages/addFriend/components/addFriendTab.jsx
- frontend/src/ui/pages/addFriend/style/addFriendTabStyle.jsx
- frontend/src/ui/pages/splitingBill/components/bottomBar.jsx
- add API for searching friends
- Fix component and css of the search bar
> Add addFriends API

- backend/src/main/java/com/sharewrap/sharewrap_backend/controllers/ItemController.java
- backend/src/main/java/com/sharewrap/sharewrap_backend/dtos/BillDto.java
- backend/src/main/java/com/sharewrap/sharewrap_backend/dtos/UserBillDto.java
- backend/src/main/java/com/sharewrap/sharewrap_backend/models/Bill.java
- backend/src/main/java/com/sharewrap/sharewrap_backend/models/Item.java
- backend/src/main/java/com/sharewrap/sharewrap_backend/models/UserBill.java
- backend/src/main/java/com/sharewrap/sharewrap_backend/services/BillService.java
- backend/src/main/java/com/sharewrap/sharewrap_backend/services/ItemService.java
- backend/src/main/java/com/sharewrap/sharewrap_backend/services/UserBillService.java
- backend/src/main/java/com/sharewrap/sharewrap_backend/services/UserService.java
- frontend/src/helpers/avatar_helper.js
- frontend/src/ui/pages/addFriend/components/addFriendTab.jsx
- frontend/src/ui/pages/addFriend/components/friendList.jsx
- frontend/src/ui/pages/billSummary/component/billsummarySpitting.jsx
- Rearrange the avatar into avatar_helper.js in helper folder
- Re-struct Backend
- Add the missing line of register(userID)
> Update Backend&Frontend function

- backend/src/main/java/com/sharewrap/sharewrap_backend/controllers/BillController.java
- backend/src/main/java/com/sharewrap/sharewrap_backend/dtos/BillDto.java
- backend/src/main/java/com/sharewrap/sharewrap_backend/models/Bill.java
- backend/src/main/java/com/sharewrap/sharewrap_backend/services/BillService.java
- frontend/src/helpers/avatar_helper.js
- frontend/src/ui/pages/addFriend/components/addFriendBottomBar.jsx
- frontend/src/ui/pages/addFriend/components/addFriendTab.jsx
- frontend/src/ui/pages/addFriend/components/friendList.jsx
- frontend/src/ui/pages/billSummary/component/billSummaryBottom.jsx
- frontend/src/ui/pages/billSummary/component/billsummarySpitting.jsx
- frontend/src/ui/pages/splitingBill/components/bottomBar.jsx
- frontend/src/ui/pages/summaryBill/compoments/equalBillSplitting.jsx
- frontend/src/ui/pages/summaryBill/compoments/summaryBillTab.jsx
- frontend/src/ui/pages/summaryBill/compoments/summeryBillAddFriend.jsx
- package-lock.json
- package.json
- Add paymentType in Bill.java
- Connect Api for CreateBill
- Fix from name to id in friends list
> Connect Api for create Bill

- backend/src/main/resources/application.properties
- frontend/src/ui/pages/home/components/bill.jsx
- frontend/src/ui/pages/home/components/hometap.jsx
- frontend/src/ui/pages/home/components/pendingBills.jsx
- Display text instead of showing an empty page on the homepage
- Move fetch code to homepagetab
- Modified backend properties
- Remove unused code
> display text in homepage, move all fetch data into hometap

- backend/src/main/java/com/sharewrap/sharewrap_backend/controllers/BillController.java
- backend/src/main/java/com/sharewrap/sharewrap_backend/services/BillService.java
- backend/src/main/java/com/sharewrap/sharewrap_backend/services/UserBillService.java
- Add delete bill api -> /bills/{bill Id}
- Add get individual bill Api -> /{userId}/bills/{Bill id}
- Fix database problem
> Add delete and get bill api

- frontend/src/ui/pages/bankAccountDetails/components/bankAccDetailsTab.jsx
- frontend/src/ui/pages/editBankAccount/components/editBankTab.jsx
- frontend/src/ui/pages/editPromptpay/components/editPromptpayTab.jsx
- Can navigate between edit bank account and prompt pay on the edit page
- Add some space on the bank account page/edit page
> Sw218 create payment details v2

- frontend/src/ui/pages/addFriend/components/addFriendBottomBar.jsx
- frontend/src/ui/pages/home/components/createBillButton.jsx
- frontend/src/ui/pages/home/components/hometap.jsx
- frontend/src/ui/pages/splitingBill/components/bottomBar.jsx
- frontend/src/ui/pages/summaryBill/compoments/summaryBillBottom.jsx
- frontend/src/ui/pages/uploadReceipt/components/methodPay.jsx
- frontend/src/ui/pages/uploadReceipt/components/shareImageContext.js
- frontend/src/ui/pages/uploadReceipt/components/uploadImage.jsx
- frontend/src/ui/pages/viewReceipt/components/viewReceiptTab.jsx
> update CircularProgress while loading data

- frontend/src/ui/pages/home/components/hometap.jsx
- frontend/src/ui/pages/pendingBill/component/pendingBillTab.jsx
- frontend/src/ui/pages/pendingBill/component/pendingBillTabNotPaid.jsx
- frontend/src/ui/pages/pendingBill/component/pendingBillTabPaid.jsx
- frontend/src/ui/pages/pendingBill/pendingBill.jsx
- frontend/src/ui/pages/pendingBill/style/pendingBillTabStyle.jsx
- Connect the api for the payment details/pending bill page
- Add circular loading (@ORPGCLUP Could you please do the css for this one?)
> Sw224 fix2

- README.md
> Update README.md in main
